//empty array (   HOTEL [   ]    )
//PROPERTIES WHAT YOU WANT FROM THEM
//REGISTER WHAT THEY DO FOR YOU 
//CREATES THE ACCOUNT / ETC
// INIT LET PET1 
//PUSH THE PETS 
//ON LOAD RENDERS ETC. TIME DISPLAY TIMES 




